spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?serverTimezone=UTC&characterEncoding=UTF-8
    username : ssafy
    password : ssafy

logging:
  level:
    root: info

jwt:
  expmin : 2
  salt : 1q2w3e4r
#mybatis:
#  type-aliases-package: com.spring.mrnoin.vo
#  mapper-locations: mybatis/mapper/**/*.xml